trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrName: 'myapr2026acr'
  imageRepository: 'html-site'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'acr-connection'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      $(tag)