apiVersion: apps/v1
kind: Deployment

metadata:
  name: html-site

spec:
  replicas: 2

  selector:
    matchLabels:
      app: html-site

  template:
    metadata:
      labels:
        app: html-site

    spec:
      containers:
      - name: html-site

        image: myapr2026acr.azurecr.io/html-site:v1

        ports:
        - containerPort: 80